(function () {

  RS_SCHOOL = window.RS_SCHOOL || {};

  RS_SCHOOL.KEYS= {
    Backquote: {
      en: "`",
      enAlt: "~",
      ru: "ё",
      ruAlt: "Ё",
    },
    KeyQ: {
      ru: "й",
      ruAlt: "Й",
      en: "q",
      enAlt: "Q",
    },
    KeyW: {
      ru: "ц",
      en: "w",
      ruAlt: "Ц",
      enAlt: "W",
    },
    KeyE: {
      ru: "у",
      en: "e",
      ruAlt: "У",
      enAlt: "E",
    },
    KeyR: {
      ru: "к",
      en: "r",
      ruAlt: "К",
      enAlt: "R",
    },
    KeyT: {
      ru: "е",
      en: "t",
      ruAlt: "Е",
      enAlt: "T",
    },
    KeyY: {
      ru: "н",
      en: "y",
      ruAlt: "Н",
      enAlt: "Y",
    },
    KeyU: {
      ru: "г",
      en: "u",
      ruAlt: "Г",
      enAlt: "U",
    },
    KeyI: {
      ru: "ш",
      en: "i",
      ruAlt: "Ш",
      enAlt: "I",
    },
    KeyO: {
      ru: "щ",
      en: "o",
      ruAlt: "Щ",
      enAlt: "O",
    },
    KeyP: {
      ru: "з",
      en: "p",
      ruAlt: "З",
      enAlt: "P",
    },
    BracketLeft: {
      ru: "х",
      en: "[",
      ruAlt: "Х",
      enAlt: "{",
    },
    BracketRight: {
      ru: "ъ",
      en: "]",
      ruAlt: "Ъ",
      enAlt: "}",
    },
    Slash: {
      ru: "/",
      en: "/",
      ruAlt: "/",
      enAlt: "|",
    },
    KeyA: {
      ru: "ф",
      en: "a",
      ruAlt: "Ф",
      enAlt: "A",
    },
    KeyS: {
      ru: "ы",
      en: "s",
      ruAlt: "Ы",
      enAlt: "S",
    },
    KeyD: {
      ru: "в",
      en: "d",
      ruAlt: "В",
      enAlt: "D",
    },
    KeyF: {
      ru: "а",
      en: "f",
      ruAlt: "А",
      enAlt: "F",
    },
    KeyG: {
      ru: "п",
      en: "g",
      ruAlt: "П",
      enAlt: "G",
    },
    KeyH: {
      ru: "р",
      en: "h",
      ruAlt: "Р",
      enAlt: "H",
    },
    KeyJ: {
      ru: "о",
      en: "j",
      ruAlt: "О",
      enAlt: "J",
    },
    KeyK: {
      ru: "л",
      en: "k",
      ruAlt: "Л",
      enAlt: "K",
    },
    KeyL: {
      ru: "д",
      en: "l",
      ruAlt: "Д",
      enAlt: "L",
    },
    Semicolon: {
      ru: "ж",
      en: ";",
      ruAlt: "Ж",
      enAlt: ":",
    },
    Quote: {
      ru: "э",
      en: "'",
      ruAlt: "Э",
      enAlt: '"',
    },
    KeyZ: {
      ru: "я",
      en: "z",
      ruAlt: "Я",
      enAlt: "Z",
    },
    KeyX: {
      ru: "ч",
      en: "x",
      ruAlt: "Ч",
      enAlt: "X",
    },
    KeyC: {
      ru: "с",
      en: "c",
      ruAlt: "С",
      enAlt: "c",
    },
    KeyV: {
      ru: "м",
      en: "v",
      ruAlt: "М",
      enAlt: "V",
    },
    KeyB: {
      ru: "и",
      en: "b",
      ruAlt: "И",
      enAlt: "B",
    },
    KeyN: {
      ru: "т",
      en: "n",
      ruAlt: "Т",
      enAlt: "N",
    },
    KeyM: {
      ru: "ь",
      en: "m",
      ruAlt: "Ь",
      enAlt: "M",
    },
    Comma: {
      ru: "б",
      en: ",",
      ruAlt: "Б",
      enAlt: "<",
    },
    Period: {
      ru: "ю",
      en: ".",
      ruAlt: "Ю",
      enAlt: ">",
    },
    Backslash: {
      ru: ".",
      en: "\\",
      ruAlt: ",",
      enAlt: "?",
    },
  
    Digit1: {
      en: 1,
      enAlt: "!",
      ru: 1,
      ruAlt: "!",
    },
    Digit2: {
      en: 2,
      enAlt: "@",
      ru: 2,
      ruAlt: '"',
    },
    Digit3: {
      en: 3,
      enAlt: "#",
      ru: 3,
      ruAlt: "№",
    },
    Digit4: {
      en: 4,
      enAlt: "$",
      ru: 4,
      ruAlt: "%",
    },
    Digit5: {
      en: 5,
      enAlt: "^",
      ru: 5,
      ruAlt: ":",
    },
    Digit6: {
      en: 6,
      enAlt: "^",
      ru: 6,
      ruAlt: ":",
    },
    Digit7: {
      en: 7,
      enAlt: "&",
      ru: 7,
      ruAlt: "?",
    },
    Digit8: {
      en: 8,
      enAlt: "*",
      ru: 8,
      ruAlt: "*",
    },
    Digit9: {
      en: 9,
      enAlt: "(",
      ru: 9,
      ruAlt: "(",
    },
    'Digit0': {
      en: '0',
      enAlt: ")",
      ru: '0',
      ruAlt: ")",
    },
    Minus: {
      en: "-",
      enAlt: "_",
      ru: "-",
      ruAlt: "_",
    },
    Equal: {
      en: "=",
      enAlt: "+",
      ru: "=",
      ruAlt: "+",
    },
    ArrowUp: {
      en: "↑",
      enAlt: "↑",
      ru: "↑",
      ruAlt: "↑",
    },
    ArrowLeft: {
      en: "←",
      enAlt: "←",
      ru: "←",
      ruAlt: "←",
    },
    ArrowDown: {
      en: "↓",
      enAlt: "↓",
      ru: "↓",
      ruAlt: "↓",
    },
    ArrowRight: {
      en: "→",
      enAlt: "→",
      ru: "→",
      ruAlt: "→",
    },
  
    AltRight: {
      en: "Alt",
      enAlt: "Alt",
      ru: "Alt",
      ruAlt: "Alt",
    },
    AltLeft: {
      en: "Alt",
      enAlt: "Alt",
      ru: "Alt",
      ruAlt: "Alt",
    },
    ShiftRight: {
      en: "Shift",
      enAlt: "Shift",
      ru: "Shift",
      ruAlt: "Shift",
    },
    ShiftLeft: {
      en: "Shift",
      enAlt: "Shift",
      ru: "Shift",
      ruAlt: "Shift",
    },
    ControlRight: {
      en: "Ctrl",
      enAlt: "Ctrl",
      ru: "Ctrl",
      ruAlt: "Ctrl",
    },
    ControlLeft: {
      en: "Ctrl",
      enAlt: "Ctrl",
      ru: "Ctrl",
      ruAlt: "Ctrl",
    },
    Space: {
      en: " ",
      enAlt: " ",
      ru: " ",
      ruAlt: " ",
    },
    Delete: {
      en: "Del",
      enAlt: "Del",
      ru: "Del",
      ruAlt: "Del",
    },
    MetaLeft: {
      en: "Win",
      enAlt: "Win",
      ru: "Win",
      ruAlt: "Win",
    },
    Backspace: {
      en: "Backspace",
      enAlt: "Backspace",
      ru: "Backspace",
      ruAlt: "Backspace",
    },
    Tab: {
      en: "Tab",
      enAlt: "Tab",
      ru: "Tab",
      ruAlt: "Tab",
    },
    CapsLock: {
      en: "CapsLock",
      enAlt: "CapsLock",
      ru: "CapsLock",
      ruAlt: "CapsLock",
    },
    Enter: {
      en: "Enter",
      enAlt: "Enter",
      ru: "Enter",
      ruAlt: "Enter",
    },
  }
})();